include("get_records.jl")
include("format_atom_index.jl")
include("format_atom_name.jl")
include("format_residue_name.jl")
include("format_residue_id.jl")
include("format_atom_coordinate.jl")
include("format_atom_occupancy.jl")
include("format_atom_beta.jl")
include("format_segment_name.jl")
include("format_atom_element.jl")
include("format_atom_charge.jl")
include("format_chain_name.jl")
include("format_ATOM.jl")
include("parse_ATOM.jl")
include("parse_symmetry.jl")
include("create_atoms.jl")
# include("format_CRYST1.jl")
# include("parse_CRYST1.jl")
# include("create_crystal_symmetry.jl")
# include("format_lattice_space_group.jl")
# include("format_lattice_lengths.jl")
# include("format_lattice_angles.jl")
# include("format_lattice_chain_count.jl")
include("save_pdb.jl")
