include("test_get_records.jl")

include("test_format_atom_index.jl")
include("test_format_atom_name.jl")
include("test_format_residue_name.jl")
include("test_format_residue_id.jl")
include("test_format_atom_coordinate.jl")
include("test_format_atom_occupancy.jl")
include("test_format_atom_beta.jl")
include("test_format_segment_name.jl")
include("test_format_atom_element.jl")
include("test_format_atom_charge.jl")

include(joinpath("parse_ATOM","runtests.jl"))
include(joinpath("format_ATOM","runtests.jl"))

include("test_create_atoms.jl")

include("test_parse_symmetry.jl")
include("test_parse_CRYST1.jl")
include("test_create_crystal_symmetry.jl")
include("test_format_lattice_space_group.jl")
include("test_format_lattice_lengths.jl")
include("test_format_lattice_angles.jl")
include("test_format_lattice_chain_count.jl")
include("test_format_CRYST1.jl")